# Generated by Django 6.1.1 on 2026-10-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_product_name', models.CharField(max_length=255, null=True)),
                ('color', models.CharField(max_length=100, null=True)),
                ('memory_size', models.CharField(max_length=100, null=True)),
                ('manufacturer', models.CharField(max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('product_code', models.CharField(max_length=100, null=True)),
                ('reviews_count', models.IntegerField(null=True)),
                ('screen_diagonal', models.CharField(max_length=50, null=True)),
                ('display_resolution', models.CharField(max_length=100, null=True)),
                ('photos', models.JSONField(blank=True, default=list, null=True)),
                ('specifications', models.JSONField(blank=True, default=dict, null=True)),
                ('link', models.URLField(max_length=500, null=True, unique=True)),
                ('status', models.CharField(default='New', max_length=50, null=True)),
            ],
        ),
    ]
