# Generated by Django 6.1.1 on 2026-10-05 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Phone',
            new_name='Phone_sel',
        ),
    ]
