# Generated by Django 6.1.1 on 2026-10-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='link',
            field=models.URLField(max_length=500, null=True, unique=True),
        ),
    ]
